'use strict';

const store = require('./store/inMemoryStore');
const brandStore = require('./store/brandStore');

const SEED_BRANDS = [
  { name: 'Everyday Basics', description: 'Timeless everyday apparel' },
  { name: 'DenimCo', description: 'Premium denim and casual wear' },
  { name: 'WoolLux', description: 'Luxury knitwear and woollens' },
  { name: 'OakCraft', description: 'Handcrafted solid wood furniture' },
  { name: 'ModernLiving', description: 'Contemporary home furniture' },
  { name: 'ProBook', description: 'Professional computing devices' },
  { name: 'SoundPro', description: 'Premium audio equipment' },
  { name: 'ViewMax', description: 'High-resolution displays' },
  { name: 'StreetStyle', description: 'Urban casual and streetwear' },
  { name: 'ActiveWear', description: 'Athletic and performance wear' },
  { name: 'TechGear', description: 'Peripherals and tech accessories' },
];

function buildSeedProducts(bm) {
  return [
    {
      name: 'Classic White Oxford Shirt',
      description: 'A timeless button-down Oxford shirt in crisp white.',
      price: 49.99, currency: 'USD', category: 'apparel', type: 'shirt',
      images: ['https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?w=400'],
      stock: 0, tags: ['formal', 'classic', 'office'],
      attributes: { color: 'white', material: 'cotton', fit: 'regular' },
      variants: [
        { options: { size: 'XS' }, stock: 10 },
        { options: { size: 'S' }, stock: 15 },
        { options: { size: 'M' }, stock: 25 },
        { options: { size: 'L' }, stock: 30 },
        { options: { size: 'XL' }, stock: 20 },
        { options: { size: 'XXL' }, stock: 12 },
      ],
      brandId: bm['Everyday Basics'].id, brandName: 'Everyday Basics',
    },
    {
      name: 'Slim Fit Dark Wash Jeans',
      description: 'Modern slim fit jeans in dark indigo wash.',
      price: 79.99, currency: 'USD', category: 'apparel', type: 'jeans',
      images: ['https://images.unsplash.com/photo-1542272604-787c3835535d?w=400'],
      stock: 0, tags: ['casual', 'everyday'],
      attributes: { color: 'indigo', material: 'denim', fit: 'slim' },
      variants: [
        { options: { size: '28x30' }, stock: 12 },
        { options: { size: '30x30' }, stock: 18 },
        { options: { size: '30x32' }, stock: 15 },
        { options: { size: '32x30' }, stock: 20 },
        { options: { size: '32x32' }, stock: 25 },
        { options: { size: '34x30' }, stock: 14 },
        { options: { size: '34x32' }, stock: 16 },
        { options: { size: '36x32' }, stock: 8 },
      ],
      brandId: bm['DenimCo'].id, brandName: 'DenimCo',
    },
    {
      name: 'Merino Wool Crew Neck Sweater',
      description: 'Lightweight merino wool sweater, perfect for layering.',
      price: 89.99, currency: 'USD', category: 'apparel', type: 'sweater',
      images: ['https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?w=400'],
      stock: 0, tags: ['winter', 'premium'],
      attributes: { color: 'white', material: 'merino wool', fit: 'regular' },
      variants: [
        { options: { size: 'XS' }, stock: 8 },
        { options: { size: 'S' }, stock: 12 },
        { options: { size: 'M' }, stock: 20 },
        { options: { size: 'L' }, stock: 25 },
        { options: { size: 'XL' }, stock: 15 },
      ],
      brandId: bm['WoolLux'].id, brandName: 'WoolLux',
    },
    {
      name: 'Solid Oak Writing Desk',
      description: 'Hand-crafted solid oak writing desk with two drawers.',
      price: 649.00, currency: 'USD', category: 'furniture', type: 'desk',
      images: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?w=400'],
      stock: 8, tags: ['home-office', 'handcrafted', 'oak'],
      attributes: { material: 'oak', color: 'natural', width_cm: 120, depth_cm: 60, height_cm: 76, drawers: 2 },
      brandId: bm['OakCraft'].id, brandName: 'OakCraft',
    },
    {
      name: '3-Seater Linen Sofa',
      description: 'Contemporary linen sofa with solid walnut legs.',
      price: 1299.00, currency: 'USD', category: 'furniture', type: 'sofa',
      images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400'],
      stock: 5, tags: ['living-room', 'modern', 'premium'],
      attributes: { material: 'linen', color: 'oatmeal', seats: 3, leg_material: 'walnut', width_cm: 220 },
      brandId: bm['ModernLiving'].id, brandName: 'ModernLiving',
    },
    {
      name: 'Rattan Side Table',
      description: 'Handwoven rattan side table with a tempered glass top and lower shelf.',
      price: 149.00, currency: 'USD', category: 'furniture', type: 'side_table',
      images: ['https://ouchcart.com/cdn/shop/files/IkantiRattanSideTable7_jpg_400x_c65f2406-bdab-4467-8fde-10c67094ec59.webp?v=1721403810&width=400'],
      stock: 18, tags: ['living-room', 'boho', 'rattan'],
      attributes: { material: 'rattan', color: 'natural', width_cm: 50, height_cm: 55 },
      brandId: bm['ModernLiving'].id, brandName: 'ModernLiving',
    },
    {
      name: 'ProBook 14 Laptop',
      description: '14-inch laptop with Intel i7, 16GB RAM, 512GB SSD.',
      price: 1149.00, currency: 'USD', category: 'electronics', type: 'laptop',
      images: ['https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400'],
      stock: 12, tags: ['sale', 'productivity', 'portable'],
      attributes: { processor: 'Intel i7', ram_gb: 16, storage_gb: 512, screen_inches: 14, color: 'silver' },
      brandId: bm['ProBook'].id, brandName: 'ProBook',
    },
    {
      name: 'Wireless Noise-Cancelling Headphones',
      description: 'Over-ear headphones with 30hr battery and active noise cancellation.',
      price: 299.00, currency: 'USD', category: 'electronics', type: 'headphones',
      images: ['https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400'],
      stock: 35, tags: ['audio', 'wireless', 'sale'],
      attributes: { color: 'midnight black', battery_hours: 30, noise_cancelling: true, connectivity: 'Bluetooth 5.2' },
      brandId: bm['SoundPro'].id, brandName: 'SoundPro',
    },
    {
      name: '27-inch 4K Monitor',
      description: 'IPS 4K UHD display with 99% sRGB coverage and USB-C.',
      price: 549.00, currency: 'USD', category: 'electronics', type: 'monitor',
      images: ['https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=400'],
      stock: 18, tags: ['home-office', '4K', 'productivity'],
      attributes: { screen_inches: 27, resolution: '3840x2160', panel: 'IPS', refresh_rate_hz: 60, color: 'black' },
      brandId: bm['ViewMax'].id, brandName: 'ViewMax',
    },
    // ── Apparel (8 new) ────────────────────────────────────────────────────
    {
      name: 'Slim Fit Graphic Tee',
      description: 'Urban graphic tee in a slim silhouette, made from soft cotton.',
      price: 24.99, currency: 'USD', category: 'apparel', type: 't-shirt',
      images: ['https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=400'],
      stock: 0, tags: ['casual', 'streetwear'],
      attributes: { material: 'cotton', fit: 'slim', colour: 'black' },
      variants: [
        { options: { size: 'XS' }, stock: 15 },
        { options: { size: 'S' }, stock: 20 },
        { options: { size: 'M' }, stock: 35 },
        { options: { size: 'L' }, stock: 30 },
        { options: { size: 'XL' }, stock: 25 },
        { options: { size: 'XXL' }, stock: 15 },
      ],
      brandId: bm['StreetStyle'].id, brandName: 'StreetStyle',
    },
    {
      name: 'Oversized Denim Jacket',
      description: 'Relaxed-fit denim jacket with distressed detailing — a streetwear staple.',
      price: 79.99, currency: 'USD', category: 'apparel', type: 'jacket',
      images: ['https://static.zara.net/assets/public/2aca/8e6b/fc0c4fe7ba7c/03dd4155a870/04551501427-e1/04551501427-e1.jpg?ts=1774002214441&w=1500'],
      stock: 0, tags: ['casual', 'streetwear', 'denim'],
      attributes: { color: 'mid blue', material: 'denim', fit: 'oversized' },
      variants: [
        { options: { size: 'XS' }, stock: 10 },
        { options: { size: 'S' }, stock: 15 },
        { options: { size: 'M' }, stock: 20 },
        { options: { size: 'L' }, stock: 18 },
        { options: { size: 'XL' }, stock: 12 },
      ],
      brandId: bm['StreetStyle'].id, brandName: 'StreetStyle',
    },
    {
      name: 'Performance Running Shorts',
      description: 'Lightweight 5-inch inseam running shorts with built-in liner and zip pocket.',
      price: 39.99, currency: 'USD', category: 'apparel', type: 'shorts',
      images: ['https://cultstore.com/cdn/shop/files/J_5081ac07-0297-4959-8ac6-27f41445a1d2.jpg?v=1742212501&width=5000'],
      stock: 0, tags: ['athletic', 'running', 'gym'],
      attributes: { material: 'polyester', fit: 'slim', colour: 'black' },
      variants: [
        { options: { size: 'XS' }, stock: 12 },
        { options: { size: 'S' }, stock: 18 },
        { options: { size: 'M' }, stock: 25 },
        { options: { size: 'L' }, stock: 22 },
        { options: { size: 'XL' }, stock: 16 },
        { options: { size: 'XXL' }, stock: 10 },
      ],
      brandId: bm['ActiveWear'].id, brandName: 'ActiveWear',
    },
    {
      name: 'Floral Midi Dress',
      description: 'Flowy chiffon midi dress with a vibrant floral print.',
      price: 69.99, currency: 'USD', category: 'apparel', type: 'dress',
      images: ['https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=400'],
      stock: 0, tags: ['casual', 'summer', 'floral'],
      attributes: { material: 'chiffon', fit: 'relaxed', colour: 'white' },
      variants: [
        { options: { size: 'XS' }, stock: 10 },
        { options: { size: 'S' }, stock: 15 },
        { options: { size: 'M' }, stock: 20 },
        { options: { size: 'L' }, stock: 18 },
        { options: { size: 'XL' }, stock: 12 },
      ],
      brandId: bm['Everyday Basics'].id, brandName: 'Everyday Basics',
    },
    {
      name: 'Lightweight Packable Jacket',
      description: 'Water-resistant nylon jacket that packs into its own pocket.',
      price: 89.99, currency: 'USD', category: 'apparel', type: 'jacket',
      images: ['https://images.unsplash.com/photo-1591047139829-d91aecb6caea?w=400'],
      stock: 0, tags: ['outdoor', 'athletic', 'waterproof'],
      attributes: { color: 'brown', material: 'nylon', waterproof: true },
      variants: [
        { options: { size: 'XS' }, stock: 8 },
        { options: { size: 'S' }, stock: 12 },
        { options: { size: 'M' }, stock: 18 },
        { options: { size: 'L' }, stock: 20 },
        { options: { size: 'XL' }, stock: 15 },
        { options: { size: 'XXL' }, stock: 10 },
      ],
      brandId: bm['ActiveWear'].id, brandName: 'ActiveWear',
    },
    {
      name: 'High-Waist Yoga Leggings',
      description: 'Four-way stretch spandex leggings with a high-rise waistband.',
      price: 54.99, currency: 'USD', category: 'apparel', type: 'leggings',
      images: ['https://cultstore.com/cdn/shop/files/704333_A.jpg?v=1749123500&width=5000'],
      stock: 0, tags: ['athletic', 'yoga', 'gym'],
      attributes: { color: 'black', material: 'spandex' },
      variants: [
        { options: { size: 'XS' }, stock: 15 },
        { options: { size: 'S' }, stock: 20 },
        { options: { size: 'M' }, stock: 28 },
        { options: { size: 'L' }, stock: 25 },
        { options: { size: 'XL' }, stock: 18 },
      ],
      brandId: bm['ActiveWear'].id, brandName: 'ActiveWear',
    },
    {
      name: 'Slim Chino Pants',
      description: 'Classic chino pants in a slim cut, versatile for office or weekend.',
      price: 64.99, currency: 'USD', category: 'apparel', type: 'chinos',
      images: ['https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=400'],
      stock: 0, tags: ['casual', 'office', 'classic'],
      attributes: { color: 'olive', material: 'cotton', fit: 'slim' },
      variants: [
        { options: { size: '28x28' }, stock: 10 },
        { options: { size: '30x30' }, stock: 15 },
        { options: { size: '30x32' }, stock: 18 },
        { options: { size: '32x30' }, stock: 20 },
        { options: { size: '32x32' }, stock: 22 },
      ],
      brandId: bm['Everyday Basics'].id, brandName: 'Everyday Basics',
    },
    {
      name: 'Cashmere Turtleneck',
      description: 'Pure cashmere turtleneck in a relaxed fit — understated luxury.',
      price: 119.99, currency: 'USD', category: 'apparel', type: 'turtleneck',
      images: ['https://images.unsplash.com/photo-1583744946564-b52ac1c389c8?w=400'],
      stock: 0, tags: ['premium', 'winter', 'luxury'],
      attributes: { color: 'black', material: 'cashmere', fit: 'relaxed' },
      variants: [
        { options: { size: 'XS' }, stock: 5 },
        { options: { size: 'S' }, stock: 8 },
        { options: { size: 'M' }, stock: 12 },
        { options: { size: 'L' }, stock: 10 },
        { options: { size: 'XL' }, stock: 7 },
      ],
      brandId: bm['WoolLux'].id, brandName: 'WoolLux',
    },
    // ── Furniture (6 new) ──────────────────────────────────────────────────
    {
      name: 'Solid Oak Bar Stool',
      description: 'Hand-turned solid oak bar stool with a saddle seat, counter height.',
      price: 229.00, currency: 'USD', category: 'furniture', type: 'stool',
      images: ['https://www.ikea.com/in/en/images/products/stig-bar-stool-with-backrest-counter-height-black-black__0948110_pe798867_s5.jpg?f=xl'],
      stock: 12, tags: ['kitchen', 'dining', 'oak'],
      attributes: { material: 'oak', color: 'natural', height_cm: 75, seat_type: 'saddle' },
      brandId: bm['OakCraft'].id, brandName: 'OakCraft',
    },
    {
      name: 'Marble Top Coffee Table',
      description: 'Statement coffee table with a genuine marble top and brushed gold legs.',
      price: 449.00, currency: 'USD', category: 'furniture', type: 'coffee_table',
      images: ['https://images.unsplash.com/photo-1567016376408-0226e4d0c1ea?w=400'],
      stock: 10, tags: ['living-room', 'modern', 'premium'],
      attributes: { material: 'marble', color: 'white', width_cm: 110, height_cm: 45 },
      brandId: bm['ModernLiving'].id, brandName: 'ModernLiving',
    },
    {
      name: 'King Platform Bed Frame',
      description: 'Solid oak king-size platform bed frame with a low-profile design.',
      price: 899.00, currency: 'USD', category: 'furniture', type: 'bed',
      images: ['https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400'],
      stock: 6, tags: ['bedroom', 'premium', 'oak'],
      attributes: { material: 'oak', color: 'natural', size: 'king', width_cm: 193 },
      brandId: bm['OakCraft'].id, brandName: 'OakCraft',
    },
    {
      name: '5-Drawer Walnut Dresser',
      description: 'Handcrafted walnut dresser with five smooth-glide drawers.',
      price: 749.00, currency: 'USD', category: 'furniture', type: 'dresser',
      images: ['https://m.media-amazon.com/images/I/71mQqLXW1LL.jpg'],
      stock: 8, tags: ['bedroom', 'storage', 'handcrafted'],
      attributes: { material: 'walnut', color: 'dark brown', drawers: 5, width_cm: 90, height_cm: 110 },
      brandId: bm['OakCraft'].id, brandName: 'OakCraft',
    },
    {
      name: 'Arc Floor Lamp',
      description: 'Contemporary arc lamp in brushed gold with a dimmable LED bulb.',
      price: 189.00, currency: 'USD', category: 'furniture', type: 'lamp',
      images: ['https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400'],
      stock: 22, tags: ['living-room', 'modern', 'lighting'],
      attributes: { color: 'gold', material: 'metal', height_cm: 180, dimmable: true },
      brandId: bm['ModernLiving'].id, brandName: 'ModernLiving',
    },
    {
      name: 'Floating Wall Shelves Set of 3',
      description: 'Minimalist MDF floating shelves — easy to install, clean aesthetic.',
      price: 89.00, currency: 'USD', category: 'furniture', type: 'shelves',
      images: ['https://rukminim2.flixcart.com/image/2880/2880/xif0q/rack-shelf/c/n/7/living-room-bedroom-1-3ofset-blk-106-np-handicraft-3-original-imahkhkhgxgprqyn.jpeg?q=90'],
      stock: 30, tags: ['storage', 'modern', 'wall'],
      attributes: { material: 'mdf', color: 'black', width_cm: 80, count: 3 },
      brandId: bm['ModernLiving'].id, brandName: 'ModernLiving',
    },
    // ── Electronics (6 new) ────────────────────────────────────────────────
    {
      name: 'Mechanical Gaming Keyboard',
      description: 'Tenkeyless mechanical keyboard with Blue switches and RGB backlight.',
      price: 129.00, currency: 'USD', category: 'electronics', type: 'keyboard',
      images: ['https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=400'],
      stock: 25, tags: ['gaming', 'productivity', 'mechanical'],
      attributes: { color: 'black', switch_type: 'blue', connectivity: 'USB', backlit: true, layout: 'TKL' },
      brandId: bm['TechGear'].id, brandName: 'TechGear',
    },
    {
      name: 'Ergonomic Wireless Mouse',
      description: 'Contoured wireless mouse with Bluetooth 5.0 and adjustable DPI.',
      price: 79.00, currency: 'USD', category: 'electronics', type: 'mouse',
      images: ['https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400'],
      stock: 40, tags: ['productivity', 'wireless', 'ergonomic'],
      attributes: { color: 'grey', connectivity: 'Bluetooth 5.0', dpi: 1600, wireless: true },
      brandId: bm['TechGear'].id, brandName: 'TechGear',
    },
    {
      name: '10.5-inch Android Tablet',
      description: '10.5-inch Android tablet with 256 GB storage and 8 GB RAM.',
      price: 499.00, currency: 'USD', category: 'electronics', type: 'tablet',
      images: ['https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?w=400'],
      stock: 18, tags: ['mobile', 'productivity', 'android'],
      attributes: { color: 'space grey', storage_gb: 256, ram_gb: 8, screen_inches: 10.5, os: 'Android' },
      brandId: bm['ProBook'].id, brandName: 'ProBook',
    },
    {
      name: 'Smart Health Watch',
      description: 'Fitness and health smartwatch with 72-hour battery and water resistance.',
      price: 249.00, currency: 'USD', category: 'electronics', type: 'smartwatch',
      images: ['https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400'],
      stock: 28, tags: ['wearable', 'health', 'fitness'],
      attributes: { color: 'black', battery_hours: 72, water_resistant: true, connectivity: 'Bluetooth 5.0' },
      brandId: bm['SoundPro'].id, brandName: 'SoundPro',
    },
    {
      name: '1080p HD Webcam',
      description: 'Full-HD webcam with built-in microphone for home-office and streaming.',
      price: 89.00, currency: 'USD', category: 'electronics', type: 'webcam',
      images: ['https://images.unsplash.com/photo-1611532736597-de2d4265fba3?w=400'],
      stock: 32, tags: ['home-office', 'streaming', 'video'],
      attributes: { color: 'black', resolution: '1920x1080', fps: 30, microphone: true },
      brandId: bm['TechGear'].id, brandName: 'TechGear',
    },
    {
      name: 'Portable Bluetooth Speaker',
      description: 'Waterproof 20W Bluetooth speaker with 12-hour playtime.',
      price: 149.00, currency: 'USD', category: 'electronics', type: 'speaker',
      images: ['https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400'],
      stock: 45, tags: ['audio', 'wireless', 'portable'],
      attributes: { color: 'blue', battery_hours: 12, connectivity: 'Bluetooth 5.0', waterproof: true, wattage: 20 },
      brandId: bm['SoundPro'].id, brandName: 'SoundPro',
    },
  ];
}

function seed() {
  const existingBrands = brandStore.list();
  if (existingBrands.length > 0) return; // already seeded — idempotent

  const seededBrands = SEED_BRANDS.map(b => brandStore.create(b));
  const brandMap = Object.fromEntries(seededBrands.map(b => [b.name, b]));

  buildSeedProducts(brandMap).forEach(p => store.create(p));

  console.log(JSON.stringify({
    timestamp: new Date().toISOString(),
    operation: 'seed',
    brands: seededBrands.length,
    products: 29,
    message: `Seeded ${seededBrands.length} brands and 29 products`,
  }));
}

module.exports = { seed };
